// AUTO-GENERATED by scripts/generate-build-info.js — do not edit manually.
export const BUILD_INFO = {
  "version": "0.1.0",
  "commitSha": "8bfcd94",
  "buildTime": "2026-07-28T15:23:38.943Z",
  "appEnv": "development",
  "deployLabel": "DEV"
} as const
