// AUTO-GENERATED by scripts/generate-build-info.js — do not edit manually.
export const BUILD_INFO = {
  "version": "0.1.0",
  "commitSha": "53e1dad",
  "buildTime": "2026-07-23T18:02:47.246Z",
  "appEnv": "development",
  "deployLabel": "DEV"
} as const
