// AUTO-GENERATED by scripts/generate-build-info.js — do not edit manually.
export const BUILD_INFO = {
  "version": "0.1.0",
  "commitSha": "ceae63d",
  "buildTime": "2026-05-31T17:35:11.137Z",
  "appEnv": "development",
  "deployLabel": "DEV"
} as const
