// AUTO-GENERATED by scripts/generate-build-info.js — do not edit manually.
export const BUILD_INFO = {
  "version": "0.1.0",
  "commitSha": "2a7e9ea",
  "buildTime": "2026-05-31T14:20:20.120Z",
  "appEnv": "development",
  "deployLabel": "DEV"
} as const
