// AUTO-GENERATED by scripts/generate-build-info.js — do not edit manually.
export const BUILD_INFO = {
  "version": "0.1.0",
  "commitSha": "2341fa6",
  "buildTime": "2026-05-30T22:32:24.077Z",
  "appEnv": "development",
  "deployLabel": "DEV"
} as const
