// AUTO-GENERATED by scripts/generate-build-info.js — do not edit manually.
export const BUILD_INFO = {
  "version": "0.1.0",
  "commitSha": "9da31e5",
  "buildTime": "2026-05-31T00:31:12.159Z",
  "appEnv": "development",
  "deployLabel": "DEV"
} as const
